Components
VladimirTatarintsev/admin-panel pull request #4
Opened 2022-03-22 14:33 UTC by VladimirTatarintsev

Многое недоработано

2022-03-22 15:05 UTC, smakhnatkin commented on src/components/Button/Button.js
> +  const buttonClass = cn(styles.button, {
cn(styles.button, styles.sectionButton, {
    [styles.colorPrimary]: color,
    [styles.sizeLarge]: size,
    [className]: !!className,
})

2022-03-22 15:05 UTC, smakhnatkin commented on src/components/Button/Button.js
> +  const buttonClass = cn(styles.button, {
но зачем 2 статических класса склеивать
сразу стили опиши в одном

я про это styles.button, styles.sectionButton,

2022-03-22 15:05 UTC, smakhnatkin commented on src/components/Button/Button.js
> +      <Bin className={styles.icon} />
кто такой мистер Бин?

2022-03-22 15:05 UTC, smakhnatkin commented on src/components/Button/Button.js
> +      <span className={styles.text}>Text here</span>
а есть ли смысл в этом спане?

2022-03-22 15:05 UTC, smakhnatkin commented on src/components/Button/Button.js
> +    [styles.sizeLargeIcon]: true,
все статические классы можно склеить сразу

2022-03-28 11:03 UTC, Muslik requested changes
Работа не завершена

2022-04-12 22:44 UTC, Muslik requested changes

2022-04-12 22:44 UTC, Muslik commented on src/components/Button/Button.jsx
> +		[styles.colorPrimary]: color==="primary",
prettier нужен

2022-04-12 22:44 UTC, Muslik commented on src/components/Button/Button.jsx
> +		[styles.colorSecondary]: color==="secondary",
тема вычисляется.
```javascript
[styles[`color_${color}`]: true
```

тоже самое касается размера

2022-04-12 22:44 UTC, Muslik commented on src/components/Button/Button.jsx
> +		[styles.sizeLargeIcon]: iconSize==="large",
Не нужны отдельные пропсы для иконки. У вас есть уже размер кнопки. У вас есть иконка. Соответственно в зависимости от размера и наличия иконки и отсутствия текста вы можете сделать стили

2022-04-12 22:44 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +	type = "checkbox",
У компонента checkbox не может быть другой type

2022-04-12 22:44 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +	const CheckboxClass = cn (styles.checkboxWrapper, className)
с маленькой буквы.
camelCase

2022-04-12 22:44 UTC, Muslik commented on src/components/Dropdown/Dropdown.jsx
> +	const DropdownClass = cn (styles.dropdownBlock, className)
С маленькой буквы

2022-04-12 22:44 UTC, Muslik commented on src/components/Label/Label.module.css
> +  margin-bottom: 8px;
Не может быть тут margin-а. Компонент понятия не должен иметь где он используется

2022-04-12 22:44 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +	name = "radio",
не нужен дефолтный name. Если его нет, это нормально что компонент будет работать неправильно

2022-04-12 22:44 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +	type = "radio",
Не нужен тут type

2022-04-12 22:44 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +			{withoutIcon || <span className={styles.customRadio}/>}
Эмм. Если withoutIcon = false, то span отобразится

2022-04-12 22:44 UTC, Muslik commented on src/module/UiKit/UiKit.jsx
> +	const STATUS = {
Вынести за пределы компонента

2022-04-12 22:44 UTC, Muslik commented on src/module/UiKit/components/InputArea/InputArea.jsx
> +export const InputAreaIncorrect = () => {
А для чего такое разделение. Это же всего лишь статическое отображение. Сделайте просто InputArea компонент и там все сразу перечислите

2022-04-12 22:44 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +			{withoutIcon || <span className={styles.customRadio}/>}
Старайтесь использовать положительный исход всегда.
withIcon && <span>

2022-04-12 22:44 UTC, Muslik commented on src/module/UiKit/components/ButtonSection/ButtonSection.jsx
> +
Папка components должны быть внутри modules/UiKit

2022-04-12 22:44 UTC, Muslik commented on src/module/UiKit/components/ButtonTable/ButtonTable.jsx
> +      <SectionButtonPrimaryLarge />
Это конечно не ошибка, то такое сильное разделение на компоненты абсолютно бессмысленно. Вы в теории вообще можете все внутри UiKit разместить. Ну или если хочется разделения, то хотя бы сделайте один компонент -> ButtonTable и в нем сразу все кнопки без подразделения их на отдельные компоненты

2022-04-12 22:44 UTC, Muslik commented on src/components/Dropdown/Dropdown.module.css
> +.dropdownSectionTop .dropdownBlock {
Я не вижу что эти классы где то используются в компоненте Dropdown

2022-04-12 22:44 UTC, Muslik commented on src/components/Button/Button.module.css
> +  display: flex;
Эти свойства и так есть в классе .button

2022-04-14 17:47 UTC, VladimirTatarintsev commented on src/components/Button/Button.module.css
> +  display: flex;
fixed

2022-04-14 17:48 UTC, VladimirTatarintsev commented on src/components/Dropdown/Dropdown.module.css
> +.dropdownSectionTop .dropdownBlock {
fixed

2022-04-14 18:07 UTC, VladimirTatarintsev commented on src/module/UiKit/components/ButtonTable/ButtonTable.jsx
> +      <SectionButtonPrimaryLarge />
fixed

2022-04-14 18:10 UTC, VladimirTatarintsev commented on src/module/UiKit/components/ButtonSection/ButtonSection.jsx
> +
А разве переиспользуемые компоненты не должны в components лежать? а те которые нужны для UiKit-а лежат в modules\UiKit\components

2022-04-14 18:17 UTC, VladimirTatarintsev commented on src/module/UiKit/components/InputArea/InputArea.jsx
> +export const InputAreaIncorrect = () => {
fixed

2022-04-14 18:18 UTC, VladimirTatarintsev commented on src/module/UiKit/UiKit.jsx
> +	const STATUS = {
fixed

2022-04-14 21:50 UTC, VladimirTatarintsev commented on src/components/Label/Label.module.css
> +  margin-bottom: 8px;
fixed

2022-04-14 21:51 UTC, VladimirTatarintsev commented on src/components/Radio/Radio.jsx
> +	name = "radio",
fixed

2022-04-14 21:51 UTC, VladimirTatarintsev commented on src/components/Radio/Radio.jsx
> +	type = "radio",
fixed

2022-04-14 21:52 UTC, VladimirTatarintsev commented on src/components/Checkbox/Checkbox.jsx
> +	type = "checkbox",
fixed

2022-04-14 21:52 UTC, VladimirTatarintsev commented on src/components/Checkbox/Checkbox.jsx
> +	const CheckboxClass = cn (styles.checkboxWrapper, className)
fixed

2022-04-15 10:08 UTC, VladimirTatarintsev commented on src/components/Button/Button.jsx
> +		[styles.colorSecondary]: color==="secondary",
fixed

2022-04-15 10:09 UTC, VladimirTatarintsev commented on src/components/Button/Button.jsx
> +		[styles.colorPrimary]: color==="primary",
присутствует, изначально ставил линт стэйдж, при коммите отрабатывает, как положено

2022-04-15 16:53 UTC, VladimirTatarintsev commented on src/components/Button/Button.jsx
> +		[styles.colorPrimary]: color==="primary",
fixed

2022-04-16 13:18 UTC, Muslik approved these changes

2022-04-17 10:21 UTC, merged